In [3]:
import pandas as pd
mercedes_df=pd.read_csv('Mercedes.data.csv')
mercedes_df

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 378 columns]

In [3]:
mercedes_df.shape

(4209, 378)

In [4]:
mercedes_df.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=378)

In [5]:
mercedes_df.shape[1]

378

In [6]:
mercedes_df.isnull().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [4]:
missing_value_df=pd.DataFrame({'Column_name':mercedes_df.columns,
                              'missing_value_count':mercedes_df.isnull().sum(),
                              'missing_value_percentage':mercedes_df.isnull().sum()/mercedes_df.shape[0]*100})
missing_value_df= missing_value_df.sort_values(by='missing_value_percentage',ascending=False)
colstodrop = list(missing_value_df[missing_value_df['missing_value_percentage']>50]['Column_name'])
colstodrop
colstodrop1 = []
y=mercedes_df['y'] 
for col in mercedes_df.columns:
    if mercedes_df[col].nunique()==mercedes_df.shape[0] or mercedes_df[col].nunique()==1:
        colstodrop1.append(col)
        
colstodrop1
TotalColumns = colstodrop + colstodrop1
TotalColumns

mercedes_df.drop(columns=TotalColumns,inplace=True)
y = mercedes_df['y']
mercedes_df.drop(columns='y',inplace=True)


In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(mercedes_df,y,test_size=0.2,random_state=66)
X_train

X0  X1  X2 X3 X4  X5 X6 X8  X10  X12  ...  X375  X376  X377  X378  X379  \
1729   y   r  as  f  d  ae  d  n    0    0  ...     0     0     0     0     0   
1336   z  aa  ai  c  d  ac  g  j    0    0  ...     1     0     0     0     0   
2372   t   b  ae  c  d   n  i  i    0    0  ...     0     0     1     0     0   
2339   s  aa  ay  c  d   n  i  o    1    0  ...     1     0     0     0     0   
1529   n   s  as  g  d  ad  i  a    0    0  ...     1     0     0     0     0   
...   ..  ..  .. .. ..  .. .. ..  ...  ...  ...   ...   ...   ...   ...   ...   
1741   y   r  as  f  d  ae  i  w    0    0  ...     0     0     0     0     0   
51    al   r   e  f  d   j  h  o    0    0  ...     0     0     0     0     0   
631    o   s   m  c  d   c  l  b    0    0  ...     0     0     1     0     0   
828   ay  aa   m  g  d  af  a  l    0    0  ...     1     0     0     0     0   
1044   w   c  as  c  d  ag  g  u    0    0  ...     0     0     1     0     0   

      X380  X382  X383  X384  X385  
1729     0     0     0     0     0  
1336     0     0     0     0     0  
2372     0     0     0     0     0  
2339     0     0     0     0     0  
1529     0     0     0     0     0  
...    ...   ...   ...   ...   ...  
1741     0     0     0     0     0  
51       0     0     0     0     0  
631      0     0     0     0     0  
828      0     0     0     0     0  
1044     0     0     0     0     0  

[3367 rows x 364 columns]

In [6]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
class LabelEncoderExt(object):
    def __init__(self):
        """
        It differs from LabelEncoder by handling new classes and providing a value for it [Unknown]
        Unknown will be added in fit and transform will take care of new item. It gives unknown class id
        """
        self.label_encoder = LabelEncoder()
        # self.classes_ = self.label_encoder.classes_

    def fit(self, data_list):
        """
        This will fit the encoder for all the unique values and introduce unknown value
        :param data_list: A list of string
        :return: self
        """
        self.label_encoder = self.label_encoder.fit(list(data_list) + ['Unknown'])
        self.classes_ = self.label_encoder.classes_

        return self

    def transform(self, data_list):
        """
        This will transform the data_list to id list where the new values get assigned to Unknown class
        :param data_list:
        :return:
        """
        new_data_list = list(data_list)
        for unique_item in np.unique(data_list):
            if unique_item not in self.label_encoder.classes_:
                new_data_list = ['Unknown' if x==unique_item else x for x in new_data_list]

        return self.label_encoder.transform(new_data_list)


In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoderExt()

for col in X_train.columns:
    if(X_train[col].dtype==object):
        le.fit(X_train[col])
        X_train[col]=le.transform(X_train[col])
        X_test[col]=le.transform(X_test[col])
X_train


C:\Users\Mounika Balireddy\Downloads\New folder\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\Users\Mounika Balireddy\Downloads\New folder\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


X0  X1  X2  X3  X4  X5  X6  X8  X10  X12  ...  X375  X376  X377  X378  \
1729  46  20  17   6   4   5   4  14    0    0  ...     0     0     0     0   
1336  47   2   8   3   4   3   7  10    0    0  ...     1     0     0     0   
2372  41   4   4   3   4  19   9   9    0    0  ...     0     0     1     0   
2339  40   2  22   3   4  19   9  15    1    0  ...     1     0     0     0   
1529  36  21  17   7   4   4   9   1    0    0  ...     1     0     0     0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...   ...   ...   ...   ...   
1741  46  20  17   6   4   5   9  23    0    0  ...     0     0     0     0   
51    10  20  26   6   4  15   8  15    0    0  ...     0     0     0     0   
631   37  21  34   3   4   9  12   2    0    0  ...     0     0     1     0   
828   20   2  34   7   4   6   1  12    0    0  ...     1     0     0     0   
1044  44   5  17   3   4   7   7  21    0    0  ...     0     0     1     0   

      X379  X380  X382  X383  X384  X385  
1729     0     0     0     0     0     0  
1336     0     0     0     0     0     0  
2372     0     0     0     0     0     0  
2339     0     0     0     0     0     0  
1529     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
1741     0     0     0     0     0     0  
51       0     0     0     0     0     0  
631      0     0     0     0     0     0  
828      0     0     0     0     0     0  
1044     0     0     0     0     0     0  

[3367 rows x 364 columns]

In [8]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
pca= PCA()

X_train_pca_df=pd.DataFrame(pca.fit_transform(X_train))
X_train_pca_df
pca.explained_variance_ratio_
plt.plot(np.cumsum(pca.explained_variance_ratio_))

plt.xlabel('Number of principal components')
plt.ylabel('Explained variance ratio')






Text(0, 0.5, 'Explained variance ratio')

In [9]:
pca_1=PCA(n_components=50)
X_train_pca_df=pd.DataFrame(pca_1.fit_transform(X_train),columns=list(range(0,50)))
X_test_pca_df=pd.DataFrame(pca_1.transform(X_test))
X_test_pca_df

0          1          2          3          4         5   \
0   -12.174352   2.039307  -2.479896   8.766808   7.106696 -1.034209   
1    -4.838892  -0.350659   2.088209   3.030975   7.049634  0.773826   
2     9.427505 -11.613341  -8.452415   5.090091  -7.550612 -1.448460   
3    -9.833911   2.922933  -0.339314  14.465205  -8.087478 -1.402180   
4   -11.395570   2.301657  14.273182   3.605039  -3.927305  3.480110   
..         ...        ...        ...        ...        ...       ...   
837 -12.133494  16.166054 -12.818798  -0.152060  -8.227457 -3.508078   
838  -2.359831 -12.697110  -6.328008  10.358171 -11.251800 -4.841587   
839   8.790640  22.676826  -6.987446 -10.380560  -1.211659  1.518427   
840   5.253778  14.656420   1.254788 -11.785056  -6.348819 -3.565816   
841   9.322435  -4.295142   7.053368 -10.177068  -1.667180 -4.847299   

           6         7         8         9   ...        40        41  \
0   -2.250910 -1.532078  0.071129 -0.272107  ... -0.735165  0.632487   
1    0.420645 -1.047167  0.818684  0.293688  ... -0.190079 -0.316165   
2   -1.962602  0.466402 -0.912640 -0.418904  ...  0.394132  0.192333   
3    0.912219 -3.026506 -1.143971  0.397060  ... -0.210463 -0.141565   
4   -2.063926 -2.164263  1.676621  0.441724  ... -0.014462  0.257417   
..        ...       ...       ...       ...  ...       ...       ...   
837 -0.947709 -0.615992 -0.301562  1.078902  ... -0.471645  0.661571   
838  1.075731  1.657571  0.552228  1.526735  ... -0.039538  0.120258   
839 -1.053116  0.459211  0.683554  2.337189  ...  0.859135  0.227211   
840  0.654248  0.755568 -2.230442 -2.360627  ... -0.135563  0.725931   
841  2.820279 -0.899350  3.244691  0.343722  ...  0.095987 -0.206463   

           42        43        44        45        46        47        48  \
0    0.474354  0.070648  0.029576  0.261108 -0.092535 -0.274808  0.166133   
1    0.123487 -0.768901  0.373919  0.062771 -0.004110  0.006824  0.422766   
2    0.135645  0.535150  0.746065  0.561812 -0.165200 -0.185215 -0.037044   
3   -0.194788 -0.174126 -0.087609 -0.019815  0.217059  0.025223  0.007409   
4    0.235577 -0.224010 -0.353157 -0.002027 -0.047223 -0.399141  0.102431   
..        ...       ...       ...       ...       ...       ...       ...   
837 -0.210634 -0.287515  0.740269  0.173270  0.024224 -0.033350  1.341508   
838  0.248616 -0.346652 -0.254390  0.161806 -0.201869 -0.001635 -0.232153   
839  0.866723 -0.057559  0.706494  0.455357 -0.764225  0.031423  0.205654   
840  0.078661 -0.274325 -0.183877  0.459931  0.414677 -0.004276 -0.201081   
841 -0.276832  0.266450 -0.195405  0.217064  0.028699  0.176600  0.076398   

           49  
0   -0.293600  
1    0.323293  
2   -0.201116  
3   -0.081399  
4    0.122125  
..        ...  
837  0.625053  
838 -0.018661  
839  0.010763  
840 -0.389989  
841  0.164776  

[842 rows x 50 columns]

In [12]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif=pd.DataFrame()
vif["VIF Factor"]=[variance_inflation_factor(X_train.values,i) for i in range(X_train.shape[1])]
vif['Column Name'] = X_train.columns
vif

C:\Users\Mounika Balireddy\Downloads\New folder\lib\site-packages\statsmodels\stats\outliers_influence.py:185: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)
C:\Users\Mounika Balireddy\Downloads\New folder\lib\site-packages\statsmodels\regression\linear_model.py:1636: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss


VIF Factor Column Name
0      2.688810          X0
1      6.701009          X1
2     20.013013          X2
3      2.924881          X3
4      1.042633          X4
..          ...         ...
359         inf        X380
360         inf        X382
361    1.455412        X383
362    2.211769        X384
363         inf        X385

[364 rows x 2 columns]

In [13]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_pca=pd.DataFrame()
vif_pca["VIF Factor_pca"]=[variance_inflation_factor(X_train_pca_df.values,i) for i in range(X_train_pca_df.shape[1])]
vif_pca['Column Name'] = X_train_pca_df.columns
vif_pca

VIF Factor_pca  Column Name
0              1.0            0
1              1.0            1
2              1.0            2
3              1.0            3
4              1.0            4
5              1.0            5
6              1.0            6
7              1.0            7
8              1.0            8
9              1.0            9
10             1.0           10
11             1.0           11
12             1.0           12
13             1.0           13
14             1.0           14
15             1.0           15
16             1.0           16
17             1.0           17
18             1.0           18
19             1.0           19
20             1.0           20
21             1.0           21
22             1.0           22
23             1.0           23
24             1.0           24
25             1.0           25
26             1.0           26
27             1.0           27
28             1.0           28
29             1.0           29
30             1.0           30
31             1.0           31
32             1.0           32
33             1.0           33
34             1.0           34
35             1.0           35
36             1.0           36
37             1.0           37
38             1.0           38
39             1.0           39
40             1.0           40
41             1.0           41
42             1.0           42
43             1.0           43
44             1.0           44
45             1.0           45
46             1.0           46
47             1.0           47
48             1.0           48
49             1.0           49

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
lin_reg=LinearRegression()
lin_reg.fit(X_train_pca_df,Y_train)
y_linreg_pred=lin_reg.predict(X_test_pca_df)
y_linreg_pred

print('R2 Score from SKlearn.metrics:---',r2_score(Y_test,y_linreg_pred))
#print('Train Score:----',lin_reg.score(X_train_pca_df,y_train))
print('R2 Score from Linear Regression Class:----', lin_reg.score(X_test_pca_df,Y_test))
# mean_squared_error(y_test,y_linreg_pred)
lin_reg.coef_

R2 Score from SKlearn.metrics:--- 0.5555084713737013
R2 Score from Linear Regression Class:---- 0.5555084713737013


array([ 1.51983321e-01,  1.99587134e-02, -1.03122123e-01, -9.56834967e-02,
        4.90874746e-02,  3.38514315e-03,  1.06317453e+00, -2.63143218e+00,
       -3.32071218e-01,  1.89646158e+00,  2.91657290e+00, -3.21341199e+00,
        1.06887316e+00, -2.39208856e+00, -5.55214828e-01,  2.24633535e+00,
       -5.82170255e+00, -3.52993367e-01, -4.79560086e-01,  1.31629973e+00,
       -9.28940141e-01,  1.42679052e+00,  1.41634665e+00,  7.12282868e-01,
       -6.34433953e-01,  1.19598671e+00, -1.79882825e-01,  8.91908667e-01,
        3.79447937e-01,  4.36902174e-01,  6.46480606e-01, -7.35533845e-01,
       -2.31468014e+00, -7.52129220e-02,  4.03638048e-01, -1.99479287e-01,
        2.58543342e-02,  8.82986764e-02, -5.65906735e-01,  4.92955025e-01,
        1.36343727e+00,  5.12105837e-01, -2.20061035e+00,  1.00794684e+00,
        1.82218525e-01,  2.15523817e-01,  5.87138291e-01,  7.53254919e-01,
        8.01178126e-01, -1.24924232e-01])

In [17]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_squared_error
dtc=DecisionTreeRegressor()
dtc.fit(X_train_pca_df,Y_train)
y_pred=dtc.predict(X_test_pca_df)
y_pred
comp_df = pd.DataFrame({'Actual_values': Y_test,'Predicted':y_pred})
comp_df
print('R2 Score from SKlearn.metrics:---',r2_score(Y_test,y_pred))
#print('Train Score:----',lin_reg.score(X_train_pca_df,y_train))
print('R2 Score from DecisionTreeRegressor Class:----', dtc.score(X_test_pca_df,Y_test))
# mean_squared_error(y_test,y_pred)
lin_reg.coef_

R2 Score from SKlearn.metrics:--- -0.1989569911467448
R2 Score from DecisionTreeRegressor Class:---- -0.1989569911467448


array([ 1.51983321e-01,  1.99587134e-02, -1.03122123e-01, -9.56834967e-02,
        4.90874746e-02,  3.38514315e-03,  1.06317453e+00, -2.63143218e+00,
       -3.32071218e-01,  1.89646158e+00,  2.91657290e+00, -3.21341199e+00,
        1.06887316e+00, -2.39208856e+00, -5.55214828e-01,  2.24633535e+00,
       -5.82170255e+00, -3.52993367e-01, -4.79560086e-01,  1.31629973e+00,
       -9.28940141e-01,  1.42679052e+00,  1.41634665e+00,  7.12282868e-01,
       -6.34433953e-01,  1.19598671e+00, -1.79882825e-01,  8.91908667e-01,
        3.79447937e-01,  4.36902174e-01,  6.46480606e-01, -7.35533845e-01,
       -2.31468014e+00, -7.52129220e-02,  4.03638048e-01, -1.99479287e-01,
        2.58543342e-02,  8.82986764e-02, -5.65906735e-01,  4.92955025e-01,
        1.36343727e+00,  5.12105837e-01, -2.20061035e+00,  1.00794684e+00,
        1.82218525e-01,  2.15523817e-01,  5.87138291e-01,  7.53254919e-01,
        8.01178126e-01, -1.24924232e-01])

In [28]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV

dtree=DecisionTreeRegressor()

hyp_dict={'max_depth':[2,3,6,7],
          'min_samples_split':[2,4,6],
          'min_samples_leaf':[3,4,5],
          'max_leaf_nodes':[4,5,7,9]}

grid_cv=GridSearchCV(dtree,param_grid=hyp_dict,cv=5)
grid_cv.fit(X_train_pca_df,Y_train)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [2, 3, 6, 7],
                         'max_leaf_nodes': [4, 5, 7, 9],
                         'min_samples_leaf': [3, 4, 5],
                         'min_samples_split': [

In [30]:
y_dtree_predict=grid_cv.predict(X_test_pca_df)
y_dtree_predict

array([110.55195246,  95.61908903, 102.30155882, 110.55195246,
       110.97229885,  94.63891144, 102.30155882,  94.63891144,
        95.61908903,  95.61908903, 101.75376068, 109.78352459,
        94.63891144, 109.78352459,  94.63891144,  94.63891144,
       110.97229885, 110.55195246, 114.5939759 ,  94.63891144,
       110.55195246,  94.63891144,  94.63891144,  94.63891144,
        94.63891144,  94.63891144,  94.63891144,  94.63891144,
        95.61908903,  77.74838235,  94.63891144, 110.55195246,
        94.63891144, 110.55195246, 102.30155882,  94.63891144,
       101.75376068, 110.55195246,  94.63891144, 110.55195246,
       109.78352459,  77.74838235, 110.97229885,  95.61908903,
       102.30155882,  77.74838235, 110.97229885, 109.78352459,
       102.30155882,  95.61908903,  94.63891144, 101.75376068,
        94.63891144,  77.74838235,  94.63891144, 110.55195246,
       109.78352459, 102.30155882,  94.63891144, 110.55195246,
        94.63891144,  95.61908903,  94.63891144, 110.97

In [18]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,mean_squared_error
rfc =  RandomForestRegressor()

rfc.fit(X_train_pca_df,Y_train)



y_rfc_pred=rfc.predict(X_test_pca_df)

y_rfc_pred
print('R2 Score from SKlearn.metrics:---',r2_score(Y_test,y_rfc_pred))
#print('Train Score:----',lin_reg.score(X_train_pca_df,y_train))
print('R2 Score from DecisionTreeRegressor Class:----', rfc.score(X_test_pca_df,Y_test))
# mean_squared_error(y_test,y_pred)
lin_reg.coef_

C:\Users\Mounika Balireddy\Downloads\New folder\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


R2 Score from SKlearn.metrics:--- 0.40847851810175895
R2 Score from DecisionTreeRegressor Class:---- 0.40847851810175895


array([ 1.51983321e-01,  1.99587134e-02, -1.03122123e-01, -9.56834967e-02,
        4.90874746e-02,  3.38514315e-03,  1.06317453e+00, -2.63143218e+00,
       -3.32071218e-01,  1.89646158e+00,  2.91657290e+00, -3.21341199e+00,
        1.06887316e+00, -2.39208856e+00, -5.55214828e-01,  2.24633535e+00,
       -5.82170255e+00, -3.52993367e-01, -4.79560086e-01,  1.31629973e+00,
       -9.28940141e-01,  1.42679052e+00,  1.41634665e+00,  7.12282868e-01,
       -6.34433953e-01,  1.19598671e+00, -1.79882825e-01,  8.91908667e-01,
        3.79447937e-01,  4.36902174e-01,  6.46480606e-01, -7.35533845e-01,
       -2.31468014e+00, -7.52129220e-02,  4.03638048e-01, -1.99479287e-01,
        2.58543342e-02,  8.82986764e-02, -5.65906735e-01,  4.92955025e-01,
        1.36343727e+00,  5.12105837e-01, -2.20061035e+00,  1.00794684e+00,
        1.82218525e-01,  2.15523817e-01,  5.87138291e-01,  7.53254919e-01,
        8.01178126e-01, -1.24924232e-01])

In [34]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

rfc=RandomForestRegressor()

hyp_dict={'max_depth':[2,3,6,7],
          'min_samples_split':[2,4,6],
          'min_samples_leaf':[3,4,5],
          'max_leaf_nodes':[4,5,7,9],
         'n_estimators': [120]}

grid_cv=GridSearchCV(rfc,param_grid=hyp_dict,cv=5)
grid_cv.fit(X_train_pca_df,Y_train)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators='warn', n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [2, 3, 6, 7],
    

In [19]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import r2_score,mean_squared_error

adr=AdaBoostRegressor()

adr.fit(X_train_pca_df,Y_train)
y_adr_pred=adr.predict(X_test_pca_df)

y_adr_pred
print('R2 Score from SKlearn.metrics:---',r2_score(Y_test,y_adr_pred))
#print('Train Score:----',lin_reg.score(X_train_pca_df,y_train))
print('R2 Score from DecisionTreeRegressor Class:----', adr.score(X_test_pca_df,Y_test))
# mean_squared_error(y_test,y_pred)
lin_reg.coef_


R2 Score from SKlearn.metrics:--- -0.35198651304110884
R2 Score from DecisionTreeRegressor Class:---- -0.35198651304110884


array([ 1.51983321e-01,  1.99587134e-02, -1.03122123e-01, -9.56834967e-02,
        4.90874746e-02,  3.38514315e-03,  1.06317453e+00, -2.63143218e+00,
       -3.32071218e-01,  1.89646158e+00,  2.91657290e+00, -3.21341199e+00,
        1.06887316e+00, -2.39208856e+00, -5.55214828e-01,  2.24633535e+00,
       -5.82170255e+00, -3.52993367e-01, -4.79560086e-01,  1.31629973e+00,
       -9.28940141e-01,  1.42679052e+00,  1.41634665e+00,  7.12282868e-01,
       -6.34433953e-01,  1.19598671e+00, -1.79882825e-01,  8.91908667e-01,
        3.79447937e-01,  4.36902174e-01,  6.46480606e-01, -7.35533845e-01,
       -2.31468014e+00, -7.52129220e-02,  4.03638048e-01, -1.99479287e-01,
        2.58543342e-02,  8.82986764e-02, -5.65906735e-01,  4.92955025e-01,
        1.36343727e+00,  5.12105837e-01, -2.20061035e+00,  1.00794684e+00,
        1.82218525e-01,  2.15523817e-01,  5.87138291e-01,  7.53254919e-01,
        8.01178126e-01, -1.24924232e-01])

In [21]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.model_selection import GridSearchCV
adr=AdaBoostRegressor()

hyp_dict={'max_depth':[3,5,6],
         'n_estimators': [50,70,100]}

grid_cv=GridSearchCV(rfc,param_grid=hyp_dict,cv=5)
grid_cv.fit(X_train_pca_df,Y_train)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestRegressor(bootstrap=True, criterion='mse',
                                             max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=10, n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [3, 5, 6], 'n_estimato

In [20]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score,mean_squared_error

gbr=GradientBoostingRegressor()
gbr.fit(X_train_pca_df,Y_train)
y_gbr_pred=gbr.predict(X_test_pca_df)
y_gbr_pred
print('R2 Score from SKlearn.metrics:---',r2_score(Y_test,y_gbr_pred))
#print('Train Score:----',lin_reg.score(X_train_pca_df,y_train))
print('R2 Score from DecisionTreeRegressor Class:----', gbr.score(X_test_pca_df,Y_test))
# mean_squared_error(y_test,y_pred)
lin_reg.coef_

R2 Score from SKlearn.metrics:--- 0.4818697283806175
R2 Score from DecisionTreeRegressor Class:---- 0.4818697283806175


array([ 1.51983321e-01,  1.99587134e-02, -1.03122123e-01, -9.56834967e-02,
        4.90874746e-02,  3.38514315e-03,  1.06317453e+00, -2.63143218e+00,
       -3.32071218e-01,  1.89646158e+00,  2.91657290e+00, -3.21341199e+00,
        1.06887316e+00, -2.39208856e+00, -5.55214828e-01,  2.24633535e+00,
       -5.82170255e+00, -3.52993367e-01, -4.79560086e-01,  1.31629973e+00,
       -9.28940141e-01,  1.42679052e+00,  1.41634665e+00,  7.12282868e-01,
       -6.34433953e-01,  1.19598671e+00, -1.79882825e-01,  8.91908667e-01,
        3.79447937e-01,  4.36902174e-01,  6.46480606e-01, -7.35533845e-01,
       -2.31468014e+00, -7.52129220e-02,  4.03638048e-01, -1.99479287e-01,
        2.58543342e-02,  8.82986764e-02, -5.65906735e-01,  4.92955025e-01,
        1.36343727e+00,  5.12105837e-01, -2.20061035e+00,  1.00794684e+00,
        1.82218525e-01,  2.15523817e-01,  5.87138291e-01,  7.53254919e-01,
        8.01178126e-01, -1.24924232e-01])

In [10]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV
gbr=GradientBoostingRegressor()
hyp_dict={'max_depth':[3,4,5],
          'min_samples_split':[2,3,4],
          'min_samples_leaf':[1,2,4],
          'max_leaf_nodes':[4,5,6],
         'n_estimators': [50,100]}
grid_cv=GridSearchCV(gbr,param_grid=hyp_dict,cv=5)
grid_cv.fit(X_train_pca_df,Y_train)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=GradientBoostingRegressor(alpha=0.9,
                                                 criterion='friedman_mse',
                                                 init=None, learning_rate=0.1,
                                                 loss='ls', max_depth=3,
                                                 max_features=None,
                                                 max_leaf_nodes=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=100,
                                                 n_iter...
                             